name: Setup Salesforce Scratch Organization
description: Setup the Salesforce scratch organization used to run the APEX and functional tests.
outputs:
  scratch-org-name:
    description: "The name to access the scratch org"
    value: ${{ steps.retrieve-org-name.outputs.org-name }}
runs:
  using: "composite"
  steps:
    # Create JWT Key File
    - run: echo "$SFDX_AUTH_JWT_KEY" > server.key
      shell: bash
    # Install NPM dependencies
    - run: |
        npm ci
        npm i -g sfdx-cli
        sfdx --version
        sfdx plugins --core
      shell: bash
    # Connect to DevHub organization
    - run: sfdx force:auth:jwt:grant --clientid $SFDX_AUTH_JWT_CLIENT_ID --jwtkeyfile server.key --username $SFDX_AUTH_JWT_USERNAME --setdefaultdevhubusername
      shell: bash
    # Setup Scratch Organization
    - run: npx ts-node -P test/acceptance/tsconfig.json utils/buildQAOrg.ts
      shell: bash
    # Return Scratch Org name as action output
    - id: retrieve-org-name
      run: echo "::set-output name=org-name::$(cat config/project-scratch-def.json | grep -oP 'orgName.*' | grep -oP '(?<=\")[a-zA-Z0-9\-]*(?=\",)')"
      shell: bash
