name: Apex Unit Tests
description: Runs the unit tests for the Apex code.
inputs:
  org-name:
    description: "The name to access the scratch org"
    required: true
  instance-url:
    description: "The URL to access the scratch org"
    required: true
  user-name:
    description: "The username to access the scratch org"
    required: true
runs:
  using: "composite"
  steps:
    # Create JWT Key File
    - run: echo "$SFDX_AUTH_JWT_KEY" > server.key
      shell: bash
    # Install NPM dependencies
    - run: |
        npm ci
        npm i -g sfdx-cli
        sfdx --version
        sfdx plugins --core
      shell: bash
    # Connect to scratch organization
    - run: sfdx force:auth:jwt:grant --clientid $SFDX_AUTH_JWT_CLIENT_ID --jwtkeyfile server.key --username ${{ inputs.user-name }} --instanceurl https://test.salesforce.com --setalias ${{ inputs.org-name }} --setdefaultusername
      shell: bash

    # Run the Apex tests
    - run: |
        mkdir -p test-results
        sfdx force:apex:test:run -r junit -w 10 > test-results/apex.xml
      shell: bash
